### ISSUE TITLE
Feature request: hook an entire object

### ISSUE THREAD

**Issue by iangilman** [cowboy/javascript-hooker#1]
I'd like to be able to easily hook every function in an object without having to loop through it and add them all myself.

**Comment by iangilman** [comment]
Also, the name of the function should be passed into the pre/post  methods in this case (or even all cases).

**Comment by cowboy** [comment]
That's interesting... but how many situations will require that you hook every single method of an object with the exact same pre- or post-hook functions?

**Comment by iangilman** [comment]
Profiling or control flow logging, for instance. Proxying would be another.

**Comment by cowboy** [comment]
I've added an example to [the readme](https://github.com/cowboy/javascript-hooker/blob/master/README.md) as well as used this [in another project](http://bit.ly/vvJlrS) already, so thanks for the great suggestion!

**Comment by iangilman** [comment]
Awesome :)
