### ISSUE TITLE
Hooking array element set

### ISSUE THREAD

**Issue by smmoosavi** [cowboy/javascript-hooker#6]
How to hook array element set. which string must be placed in `?` postion

``` js
var x = [1,2,3];
hooker.hook(x,'?',function() {
  console.log(arguments, "passed");
});
x[1] = 'Hi'; // log: [1, "Hi"] passed
```

**Comment by cowboy** [comment]
Unfortunately, the current JavaScript doesn't allow getting/setting arbitrary Array elements to be hooked.
